### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by jessrod11** [nss-evening-cohort-7/bandz-justin-thyme#2]

**Comment by colinlwhite** [comment]
# Story 

As a user, in order to navigate the site, I need to have a functional navigation bar. 

# Acceptance Criteria 

**When** the page loads there should be a navigation bar 
**And** when you click on a link/text it should take you to the correct webpage
**And** when you click on a link/text you should see the corresponding URL in the browser’s address bar

 # Technical Notes

- Create nav element
- Create ul element
- Create li element
- Add anchor tag within the <li> elements 
- Add href attribute to anchor tag
- Link the each html file below

**Comment by colinlwhite** [comment]
<img width="707" alt="screen shot 2018-03-13 at 9 21 34 pm" src="https://user-images.githubusercontent.com/36483871/37380035-aa68a500-2704-11e8-8408-2cc866550df8.png">
